apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app  : apache
    env  : test
    owner: BartoshukVadim
spec:
  replicas: 2
  selector:
    matchLabels:
      project: k8s-deploy
  template:
    metadata:
      labels:
        project: k8s-deploy
    spec:
      containers:
        - name : k8s-html
          image: bartolamey/kub_deploy:latest
          ports:
            - containerPort: 80