apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app  : apache
    env  : test
    owner: BartoshukVadim
spec:
  replicas: 2
  selector:
    matchLabels:
      project: k8s-deploy
  template:
    metadata:
      labels:
        project: k8s-deploy
    spec:
      containers:
        - name : k8s-html
          image: bartolamey/kub_deploy'%env%'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-deploy-service
  labels:
    env: test
    owner: BartoshukVadim
spec:
  selector:
    project: k8s-deploy
  ports:
    - name       : app-list
      protocol   : TCP
      port       : 80
      targetPort : 80
  type: LoadBalancer